### ISSUE TITLE
feat: add local storage capability to store state even after reloading the page

### ISSUE THREAD

**Issue by profnandaa** [kanyuga/killer-counter#20]
**Current state:**
When you reload the page, all the data is lost.

**Desired state:**
Retain the data even after reload. Only reset after clicking on _New Game_.

**Comment by kanyuga** [comment]
Mistakenly closed by PR #34

**Comment by profnandaa** [comment]
@kanyuga - did you deploy to Github pages? Can't see the changes yet.
